# This is a basic workflow to help you get started with Actions

name: CI-and-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # 3.4.0
        with:
          fetch-depth: 1
          lfs: 'false'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm -v 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "this is my build file" > file2.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: file2.txt

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # 3.4.0
        with:
          fetch-depth: 1
          lfs: 'false'

      - name: Run a one-line script
        run: npm -v 

          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: build

      - name: Run a one-line script
        run: cat file2.txt
      
      - name: release mode echo
        run: echo ${{ vars.RELEASE_MODE }}
          
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment: prod
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: build

      - name: Run a one-line script
        run: cat file2.txt
        
      - name: release mode echo
        run: echo ${{ vars.RELEASE_MODE }}
        
